### ISSUE TITLE
Crash on spawn generation

### ISSUE THREAD

**Issue by d4rkm0nkey** [TheGrimsey/Stoneholm#8]
**Describe the bug**
Sometimes when generating a new world, the game crashes with following error:

```
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: java.util.concurrent.CompletionException: java.lang.NullPointerException
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: Caused by: java.lang.NullPointerException
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at net.minecraft.class_3485.method_15094(class_3485.java:545)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at net.minecraft.class_3485.method_15091(class_3485.java:54)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at net.minecraft.class_3781.method_27233(class_3781.java:83)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at net.minecraft.class_3781.method_16627(class_3781.java:108)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at net.minecraft.class_3778$class_4182.method_19306(class_3778.java:141)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at net.minecraft.class_3778$class_4182.method_27232(class_3778.java:54)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at net.minecraft.class_3778.method_30419(class_3778.java:305)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at net.thegrimsey.stoneholm.structures.UnderGroundVillageStructure$Start.init(UnderGroundVillageStructure.java:72)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at net.thegrimsey.stoneholm.structures.UnderGroundVillageStructure$Start.method_16655(UnderGroundVillageStructure.java:48)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at net.minecraft.class_3195.method_28657(class_3195.java:261)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at net.minecraft.class_5312.method_28622(class_5312.java:35)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at net.minecraft.class_2794.method_28508(class_2794.java:278)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at net.minecraft.class_2794.method_16129(class_2794.java:267)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at net.minecraft.class_2806.method_16556(class_2806.java:51)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at net.minecraft.class_2806.mdec2d72$lambda$runGenerationTask$0$7(class_2806.java:1543)
[14:37:42] [ServerLevel[New World] - Light/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
```

**To Reproduce**
1. Install mods
2. Generate multiple worlds

**Expected behavior**
No crash

**Mod version:** 1.2.1

**Fabric API version:** 0.36.0+1.16

**Minecraft version:** 1.16.5

**Additional Context:**
My mods:
- [Fabric] Wildfire Female Gender Mod-2.7.1
- Adorn-1.14.1+1.16.5
- adventurez-1.2.6
- alaskanativecraft-1.2.2
- AnvilFix-1.2.1-1.16
- architectury-1.20.28-fabric
- bclib-0.1.45
- better-end-0.9.8.5-pre
- better-nether-5.0.7
- betterbiomeblend-1.16.4-1.1.8-fabric
- BetterCaves-Fabric-1.16.5-1.2
- betterdroppeditems-1.2.4-1.16.2
- BetterMineshafts-Fabric-1.16.4-1.0.2
- BetterStrongholds-Fabric-1.16.5-1.0
- c2me-fabric-mc1.16.5-0.1-SNAPSHOT-all
- Cardinal-Components-API-2.8.3
- cavebiomes-0.6.2
- charm-fabric-1.16.5-2.3.2
- charmonium-fabric-1.16.5-2.3.2
- ChickenDropFeathers-1.0-fabric-0.31.0+1.16
- cleancut-mc1.16-2.1-fabric
- cloth-api-1.4.9
- cloth-config-4.11.26-fabric
- colorunchained-1.1.1-1.16.4
- compostable-rottenflesh-1.0.0
- Controlling-For-Fabric-1.1.3
- Couplings-1.3.6
- cullleaves-2.1.0
- DamageTilt-1.16-fabric-0.1.2
- dark-loading-screen-1.6.3
- direbats-1.1.1+1.16.5-fabric
- DualRiders-1.0.5
- dynamic-fps-2.0.2
- dynamic-music-1.2.0
- DynamicSoundFilters-1.2.0+1.16.5
- easiervillagertrading-1.16.5-fabric0.30.0-1.5.4
- EditSign-Fabric-1.16.5-2.2.0
- enchantment-lore-1.1.1+MC1.16.1-1.16.5
- EnchantmentDescriptions-Fabric-1.16.5-2.0.6
- endplus-mod-1.0.1
- enhancedblockentities-0.4--1.16.x
- EntityCulling-Fabric-1.3.0
- fabric-api-0.36.0+1.16
- fabric-language-kotlin-1.6.1+kotlin.1.5.10
- fabricmod_VoxelMap-1.10.15_for_1.16.5
- fallingleaves-1.6.0+1.16.5
- fast-leaves-fabric-1.16.4-1.0.2
- faster-minecarts-1.0.1
- fatxporbs-0.0.9+1.16.4
- ferritecore-2.0.4-fabric
- geckolib-fabric-1.16.5-3.0.40
- Gilded-Netherite-1.0.0
- here-be-no-dragons-1.0.0
- HomeCamp-1.16.4-1.0.3
- horse-stats-vanilla-4.1.8
- illuminations-1.5.1
- inmis-2.2.1-1.16.5
- iris-mc1.16.5-1.1.0
- item-model-fix-1.0.2+1.16
- itemscroller-fabric-1.16.4-0.15.0-dev.20210111.205029
- krypton-0.1.2
- kubejs-fabric-1605.3.11-build.35
- lambdynamiclights-fabric-1.3.4+1.16
- lapisreserve-1.0.7
- lazydfu-0.1.2
- malilib-fabric-1.16.4-0.10.0-dev.21+arne.5
- Mambience-3.1.1+1.16.5
- medievalweapons-1.1.3
- mobz-2.4.6
- modmenu-1.16.9
- MoEnchantments-1.15.0
- Monster-of-the-ocean-depths-3.1-1.16.5
- monsters-in-the-closet-1.0.2+1.16
- more_crafting_tables_v0.1.3_1.16.x
- mostructures-1.2.0-1.16.5
- NoAngleBrackets-1.0.1
- norecipebook-2.1+1.16.5
- notes-1.16.2-1.0.4
- okzoomer-4.0.1+1.16.2
- phosphor-fabric-mc1.16.3-0.7.2+build.12
- pling-1.3.0
- polymorph-fabric-0.0.10-1.16.5
- randompatches-2.4.5-fabric
- ratsmischief-1.1.2
- repurposed_structures-1.16.5-1.11.6-fabric
- rer-2.1.5
- rhino-1605.1.1-build.23
- right-click-clear-2.0.2
- rightclickharvest-1.2.3
- RoughlyEnoughItems-5.12.248
- ScreenshotToClipboardFabric-1.0.6
- seamless-loading-screen-1.3.4+1.16.2
- skin-restorer-1.0.1
- slight-gui-modifications-1.7.1
- smoothboot-fabric-1.16.5-1.6.0
- stoneholm-1.2.1.jar
- talking-villagers-1.1.3
- Terra-fabric-5.3.3-BETA+5dd00db8-shaded-mapped
- theparakeetmod-Fabric-1.16.3-1.0.6
- TheVeggieWay_Fabric_1.16.5-1.0.41
- ToolStats-fabric-1.16.5-1.0.1
- tooltipfix-1.0.2-1.16
- torohealth-1.16.4-fabric-4
- traverse-3.3.2
- unlitcampfire-1.3.0-fabric-1.16.2+
- untitledduckmod-0.2.2-fabric
- villagernames-1.16.4-1.6.0
- voicechat-1.16.5-1.6.4
- wraith-waystones-2.0.1
- xp_storage-1.4+1.16.5
- YungsApi-1.16.5-Fabric-5

**Comment by TheGrimsey** [comment]
> c2me-fabric-mc1.16.5-0.1-SNAPSHOT-all

c2me tries to do multithreaded chunk generation. It is not stable enough to be used yet. This error is wholly on it as vanilla does not use ``java.base/java.util.concurrent.ConcurrentHashMap`` in that point of generation.

**Comment by TheGrimsey** [comment]
Should probably report this as an error to them.

**Comment by d4rkm0nkey** [comment]
ok thanks! Tried without it and no crash so far.
